### ISSUE TITLE
Submission Test

### ISSUE THREAD

**Issue by k4rth33k** [k4rth33k/covid-xray#1]
**Before you start, please follow this format for your issue title**:  
TEAM NAME - PROJECT NAME - THEME NAME

## ℹ️  Project information

1.  **Theme:** Deep Tech - Detection of COVID-19 with X-ray images.
2.  **Project Name:**  COVID-Kicker
    
3.  **Short Project Description:**  A fully automated, deep learning powered REST API to detect COVID-19 from X-ray images.
    
4.  **Team Name:**  binarySunset
    
5.  **Team Members:** Kartheek Surampudi (@k4rth33k), Naga Nikshith (@naganikshith04), Hruday Pavithrachary (@hruday007)
    
6.  **Demo Link:**  _(if any, this might contain a website/ mobile application link/ short video, etc.)_
    
7.  **Repository Link(s):**  [https://github.com/k4rth33k/covid-xray](https://github.com/k4rth33k/covid-xray)
    

## 🔥  Pitch

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The COVID-19 pandemic is not new to anyone. The number of cases is growing so fast that the pace at which the counter-measures are being conducted is not enough. Many individuals and companies have built deep learning-based solutions around the publicly available datasets but the data is flowing in as new cases keep popping up.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This project proposes a solution to keep up with the new data. A REST API to serve the deep learning model to detect COVID-19 from XRay images and an automated pipeline that trains the model with the new data and updates the API.

## 🔦  Additional Notes

_(Optional)_

## ✅  Checklist

**Before you post the issue**:

-   You have followed the issue title format.
-   You have mentioned the correct labels.
-   You have provided all the information correctly.

**Comment by naganikshith04** [comment]
https://github.com/naganikshith04/covidDetector
are ee link kuda ad chyu ra andulo

**Comment by k4rth33k** [comment]
--!--
